[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Use custom framework with Bluepad32 integrated BTstack
platform_packages =
    framework-arduinoespressif32 @ https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

# Hardware Specifics for N16R8 (16MB Flash, 8MB Octal PSRAM)
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.psram_type = opi

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM

lib_deps =
    madhephaestus/ESP32Servo @ ^1.1.0

# Optional: Speed up upload if your cable supports it
upload_speed = 921600
monitor_speed = 115200